/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs.troubleshooting'
import { Route as DocsSkillsRouteImport } from './routes/docs.skills'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsPublishingRouteImport } from './routes/docs.publishing'
import { Route as DocsMcpRouteImport } from './routes/docs.mcp'
import { Route as DocsInstallRouteImport } from './routes/docs.install'
import { Route as DocsCommandsRouteImport } from './routes/docs.commands'
import { Route as DocsArchitectureRouteImport } from './routes/docs.architecture'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSkillsRoute = DocsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPublishingRoute = DocsPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMcpRoute = DocsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallRoute = DocsInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCommandsRoute = DocsCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/docs': typeof DocsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/publishing': typeof DocsPublishingRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/skills': typeof DocsSkillsRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/publishing': typeof DocsPublishingRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/skills': typeof DocsSkillsRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/docs': typeof DocsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/publishing': typeof DocsPublishingRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/skills': typeof DocsSkillsRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/docs'
    | '/sitemap.xml'
    | '/docs/architecture'
    | '/docs/commands'
    | '/docs/install'
    | '/docs/mcp'
    | '/docs/publishing'
    | '/docs/quickstart'
    | '/docs/skills'
    | '/docs/troubleshooting'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/sitemap.xml'
    | '/docs/architecture'
    | '/docs/commands'
    | '/docs/install'
    | '/docs/mcp'
    | '/docs/publishing'
    | '/docs/quickstart'
    | '/docs/skills'
    | '/docs/troubleshooting'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/docs'
    | '/sitemap.xml'
    | '/docs/architecture'
    | '/docs/commands'
    | '/docs/install'
    | '/docs/mcp'
    | '/docs/publishing'
    | '/docs/quickstart'
    | '/docs/skills'
    | '/docs/troubleshooting'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  DocsRoute: typeof DocsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/skills': {
      id: '/docs/skills'
      path: '/skills'
      fullPath: '/docs/skills'
      preLoaderRoute: typeof DocsSkillsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/publishing': {
      id: '/docs/publishing'
      path: '/publishing'
      fullPath: '/docs/publishing'
      preLoaderRoute: typeof DocsPublishingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/mcp': {
      id: '/docs/mcp'
      path: '/mcp'
      fullPath: '/docs/mcp'
      preLoaderRoute: typeof DocsMcpRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/install': {
      id: '/docs/install'
      path: '/install'
      fullPath: '/docs/install'
      preLoaderRoute: typeof DocsInstallRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/commands': {
      id: '/docs/commands'
      path: '/commands'
      fullPath: '/docs/commands'
      preLoaderRoute: typeof DocsCommandsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsCommandsRoute: typeof DocsCommandsRoute
  DocsInstallRoute: typeof DocsInstallRoute
  DocsMcpRoute: typeof DocsMcpRoute
  DocsPublishingRoute: typeof DocsPublishingRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsSkillsRoute: typeof DocsSkillsRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsCommandsRoute: DocsCommandsRoute,
  DocsInstallRoute: DocsInstallRoute,
  DocsMcpRoute: DocsMcpRoute,
  DocsPublishingRoute: DocsPublishingRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsSkillsRoute: DocsSkillsRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  DocsRoute: DocsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
